[Metadata]
Name = ExtraExpandedEnhancedEcounters!-lite
Author = Within Amnesia, with fixes by Graion Dilach
Description = Additional minor encounters for BGEE/EET.
# Readme =
Forum = https://forums.beamdog.com/discussion/73749
Download = https://github.com/Sauler89/ExtraExpandedEnhancedEncounters-lite
LabelType = GloballyUnique
Before = EET_end
After = EET, AC_QUEST
